import pygame

pygame.init()

BLUE_TEAM = 'blue-team'
RED_TEAM = 'red-team'

UP = 'UP'
DOWN = 'DOWN'
RIGHT = 'RIGHT'
LEFT = 'LEFT'
UP_LEFT = 'UP_LEFT'
UP_RIGHT = 'UP_RIGHT'
DOWN_LEFT = 'DOWN_LEFT'
DOWN_RIGHT = 'DOWN_RIGHT'

PLAYER_SIZE = 60

SPEED_DEFAULT = 4
SQRT_2 = 1.4142

FPS = 200

TEAMSIZE = 4

BACKGROUND_WIDTH = 1100
BACKGROUND_HEIGHT = 620

GAP_SIZE_WIDTH = 35
GAP_SIZE_HEIGHT = 17

GAME_WIDTH = BACKGROUND_WIDTH - 2 * GAP_SIZE_WIDTH      # 1030
GAME_HEIGHT = BACKGROUND_HEIGHT - 2 * GAP_SIZE_HEIGHT   # 586

TABLE_SCORE_WIDTH = BACKGROUND_WIDTH
TABLE_SCORE_HEIGHT = 60

RECT_GAME = pygame.Rect(GAP_SIZE_WIDTH, TABLE_SCORE_HEIGHT + GAP_SIZE_HEIGHT, GAME_WIDTH, GAME_HEIGHT)

TOP_LEFT = (0 + GAP_SIZE_WIDTH, TABLE_SCORE_HEIGHT + GAP_SIZE_HEIGHT)

WINDOW_WIDTH = BACKGROUND_WIDTH
WINDOW_HEIGHT = BACKGROUND_HEIGHT + TABLE_SCORE_HEIGHT

TEXT_WIDTH = WINDOW_WIDTH - GAME_WIDTH
TEXT_HEIGHT = WINDOW_HEIGHT

BORDER_WIDTH = 1

SIZE_ITEM = 40

WIDTH_OF_PLAY_AGAIN_BOARDING = WINDOW_WIDTH / 2
HEIGHT_OF_PLAY_AGAIN_BOARDIG = WINDOW_HEIGHT / 2

WIDTH_OF_PAUSE_GAME = WINDOW_WIDTH / 3
HEIGHT_OF_PAUSE_GAME = WINDOW_HEIGHT / 2

FRAMS_TO_RERENDER_NEW_OBJECT = 50

WITH_SETTING_BOARD = WINDOW_WIDTH / 3
HEIGHT_SETTING_BOARD = WINDOW_HEIGHT

GOAL_WIDTH = 132

FONT30 = pygame.font.Font('assets/fonts/Muli-Regular.ttf', 30)
FONT30B = pygame.font.Font('assets/fonts/Muli-Bold.ttf', 30)
FONT60B = pygame.font.Font('assets/fonts/Muli-Bold.ttf', 60)
